# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_from', models.CharField(max_length=20)),
                ('noti_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
