# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='noti_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='noti_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_time',
            field=models.DateTimeField(),
        ),
    ]
