# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171220_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
