# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import info_assistant.custom_file_system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=info_assistant.custom_file_system.storage.ImageStorage(), upload_to='book_images/'),
        ),
    ]
