# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171223_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
